project:
  type: website
  output-dir: docs
  
website: 
  title: "Maimoona's Website"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - about.qmd
      - href: STAT 244-SC.qmd
        text: STAT 244-SC
      - href: teaching.qmd
        text: Teaching Experience
        
format: 
  html: 
    theme: cyborg
    css: styles.css
    toc: true
  

editor: visual

